#!/bin/sh

export PATH="${PATH}:$HOME/.config/bspwm"

# Autostart
xrandr --output eDP1 --mode 1920x1080 --rate 60.01
hsetroot -fill $WALLPAPERS/doomguy.png

killall -q -9 sxhkd poly redshift picom

sxhkd &
poly &
redshift -v -c $HOME/.config/redshift.conf &
picom --config $HOME/.picom.conf -b

# Configuration
bspc monitor -d 1 2 3 4 5 6
bspc config border_width            5
bspc config window_gap			    10
bspc config split_ratio			    0.5
bspc config borderless_monocle		true
bspc config gapless_monocle		    true
bspc config focus_follows_pointer	true
bspc config normal_border_color		"#78787e"
bspc config focused_border_color	"#e2e4e5"
bspc config presel_feedback_color	"#2c3939"
bspc config initial_polarity		second_child

# Rules
bspc rule -a "Firefox"              desktop='^1'		follow=on
bspc rule -a TelegramDesktop 		desktop='^2'		follow=on
bspc rule -a "realvnc-vncviewer"	desktop='^5' 		follow=on       state=floating      center=true

bspc rule -a "Firefox":"Places"		state=floating		follow=on	    center=true
bspc rule -a "Firefox":"Browser"	state=floating		follow=on	    center=true
bspc rule -a Lxappearance 		    state=floating 		follow=on	    center=true
bspc rule -a Sxiv 			        state=floating 		center=true
bspc rule -a Alacritty			    state=floating 		follow=on	    center=true
bspc rule -a "org.remmina.Remmina"  state=floating      follow=on       center=true
