#! /bin/sh

export PATH="${PATH}:$HOME/.scripts"
export PATH="${PATH}:$HOME/.config/bspwm"

# Autostart
hsetroot -fill ~/Pictures/Wallpapers/johnwick_3.png

killall -q -9 sxhkd dunst poly

sxhkd &
dunst &
poly &

# Configuration
bspc monitor -d I II III IV V VI VII VIII 
bspc config border_width		5
bspc config window_gap			10
bspc config split_ratio			0.5
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_follows_pointer	true
bspc config normal_border_color		"#407076"
bspc config focused_border_color	"#dee3e0"
bspc config presel_feedback_color	"#2c3939"
bspc config initial_polarity		second_child

# Rules
bspc rule -a "Firefox" desktop='^1' follow=on
bspc rule -a "Firefox":"Places" state=floating follow=on center=true
bspc rule -a "Firefox":"Browser" state=floating follow=on center=true
bspc rule -a TelegramDesktop desktop='^2' follow=on 
bspc rule -a st-256color desktop='^3' follow=on
bspc rule -a Thunar  desktop='^4' follow=on state=floating center=true
bspc rule -a ncmpcpp desktop='^5' follow=on state=floating center=true
bspc rule -a win10 desktop='^6' follow=on 
bspc rule -a win2016 desktop='^7' follow=on 
bspc rule -a debian desktop='^8' follow=on 

bspc rule -a Lxappearance state=floating follow=on center=true
bspc rule -a spicy state=tiling follow=on
bspc rule -a Sxiv state=floating center=true
bspc rule -a Qemu-system-x86_64 state=floating center=true
