#! /bin/sh

# Load sxhkd
sxhkd &

# Custom applications
xsetroot -cursor_name left_ptr &
dunst &
. "${HOME}/.cache/wal/colors.sh"
~/.config/polybar/launch.sh &
feh --bg-scale "$(< "${HOME}/.cache/wal/wal")" &
# compton -b --config ~/.compton.conf &

# Rules bspwm

bspc monitor -d web telegram terminal files music work remote

bspc config border_width        10
bspc config window_gap          30

bspc config split_ratio          0.52
#bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Firefox desktop='^1' follow=on
bspc rule -a Firefox:Places desktop='^1' follow=on state=floating follow=on
bspc rule -a TelegramDesktop desktop='^2' follow=on 
bspc rule -a St desktop='^3' follow=on
bspc rule -a ranger desktop='^4' follow=on state=floating
bspc rule -a ncmpcpp desktop='^5' follow=on state=floating

bspc rule -a Lxappearance state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a feh state=floating follow=on

bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
