#!/usr/bin/env bash
#
#
# Testing sysinfo
# By: Marcelo Alves
# No Copyright, license or any shit. Intelectual property doesn't exists.

# System information

os="$(sed -rn '/^NAME/ s/^NAME="?([a-z A-Z]+).?$/\1/p' /etc/os-release)"
kernel="$(uname -sr)"
hostname="$(uname -n)"
cpu="$(uname -p)"
shell="$(echo $SHELL)"

mem_info() {
	total=$(free -m | awk '{print $2}' | sed -n '2p')
	used=$(free -m | awk '{print $3}' | sed -n '2p')
	
	printf "${used}MiB / ${total}MiB\n"
}

# Clear screen
clear 

# Print sysinfo
cat <<EOF 

Well, some information about your system.
Let's go.

OS:		${os}
Hostname:	${hostname}
Kernel:		${kernel}
Processor:	${cpu}
Memory:		$(mem_info)
Shell:		${shell}

EOF







# Testing area
#
# userandhost="$(echo $(whoami)@$(uname -n))"
# mem_total="$(cat /proc/meminfo | awk '/MemTotal/ {printf $2}')"
# mem_usage="$(cat /proc/meminfo | awk '/Active/ {print $2}' | head -n 1)"
# mem_info="$(($mem_usage / 1024))MiB / $(($mem_total / 1024))MiB"
