#!/usr/bin/env bash
#
#
# Testing sysinfo

# System information

os="$(sed -rn '/^NAME/ s/^NAME="?([a-z A-Z]+).?$/\1/p' /etc/os-release)"
kernel="$(uname -sr)"
hostname="$(uname -n)"
cpu="$(cat /proc/cpuinfo | awk -F': | @' '/model name|Processor|^cpu model|chip type|^cpu type/ {printf $2; exit}')"
mem_total="$(cat /proc/meminfo | awk '/MemTotal/ {printf $2}')"
mem_usage="$(cat /proc/meminfo | awk '/Active/ {print $2}' | head -n 1)"
mem_info="$(($mem_usage / 1024))MiB / $(($mem_total / 1024))MiB"
shell="$(echo $SHELL)"



# Clear screen
clear 

# Print sysinfo
cat <<EOF 

Well, some information about your system.
Let's go.

OS:		${os}
Hostname:	${hostname}
Kernel:		${kernel}
Processor:	${cpu}
Memory:		${mem_info}
Shell:		${shell}

EOF



#
#
#
# Some bloat and trash
# userandhost="$(echo $(whoami)@$(uname -n))"
