#!/bin/sh
# Backup Gentoo and home configs.

portage=/etc/portage/
xorg=/etc/X11/xorg.conf.d

dotfiles=$HOME/dotfiles
gentoo_dotfiles=$dotfiles/gentoo

# Backup Gentoo configs.
cp $portage/{bashrc,make.conf,package.accept_keywords,package.license,package.mask,package.use} $gentoo_dotfiles
cp -r $xorg $gentoo_dotfiles/
zcat /proc/config.gz > $gentoo_dotfiles/config_kernel

# Backup home configs.
cp -r $HOME/{.asoundrc,.bash_profile,.bash_logout,.vimrc,.xinitrc} $dotfiles
cp -r $HOME/.config/{bspwm,dunst,mpd,polybar,rofi,sxhkd} $dotfiles/.config
cp -r $HOME/.scripts/ $dotfiles
cp -r $HOME/.local/share/fonts/* $dotfiles/fonts
cp -r $HOME/.ncmpcpp $dotfiles
cp -r $HOME/packages $dotfiles

echo "Done."
