#!/bin/bash
set -x
# NAT Network with IP forwarding

# Bridge device
BRIDGE=lxcbr0

# Network configuration
NETWORK=10.0.0.0
NETMASK=24
GATEWAY=10.0.0.1

# Host interface
LINK=wlp3s0

# Bridge device
create_bridge() {
	ip link add name "$BRIDGE" type bridge
	ip link set "$BRIDGE" up
	ip addr flush dev "$BRIDGE" scope global
	ip addr add "$GATEWAY"/"$NETMASK" dev "$BRIDGE"
	ip link set "$BRIDGE" up
}

# Check if device exists
ifconfig $BRIDGE
device=$?

if [ $device == "0" ]; then
	ip link delete dev "$BRIDGE"
	create_bridge
else
	create_bridge
fi

# Start IP forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward

# Setup iptables rules
iptables -t nat -A POSTROUTING -s "$NETWORK"/"$NETMASK" -o "$LINK" -j MASQUERADE

echo "Done"
